# Generated by Django 5.0.7 on 2024-07-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0004_rename_desc_contact_message_remove_contact_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='desc',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
