# Generated by Django 5.0.7 on 2024-07-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0009_counselling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('current_university', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('comments', models.TextField(blank=True)),
                ('stripe_token', models.CharField(max_length=100)),
            ],
        ),
    ]
