# Generated by Django 5.0.7 on 2024-07-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0010_placement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='stripe_token',
        ),
        migrations.AlterField(
            model_name='placement',
            name='resume',
            field=models.FileField(null=True, upload_to='resumes/'),
        ),
    ]
