# Generated by Django 5.0.7 on 2024-07-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0011_remove_placement_stripe_token_alter_placement_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='RMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('Technical Issue', 'Technical Issue'), ('Facilities', 'Facilities'), ('General Inquiry', 'General Inquiry')], max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
