# Generated by Django 5.0.7 on 2024-07-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0012_rms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('student_type', models.CharField(max_length=20)),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('exam_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('maintenance_charges', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
