# Generated by Django 5.0.7 on 2024-07-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0013_feees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('room_type', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('meal_plan', models.CharField(max_length=20)),
                ('meal_days', models.IntegerField()),
                ('laundry_service', models.BooleanField(default=False)),
                ('gym_access', models.BooleanField(default=False)),
            ],
        ),
    ]
