# Generated by Django 5.0.7 on 2024-07-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0014_hostel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('transport_option', models.CharField(choices=[('shuttle', 'Shuttle Service'), ('citybus', 'City Bus Service'), ('custom', 'Custom Route')], max_length=20)),
                ('distance_covered', models.IntegerField()),
            ],
        ),
    ]
