# Generated by Django 5.0.7 on 2024-07-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0015_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('current_university', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('comments', models.TextField()),
            ],
        ),
    ]
