# Generated by Django 5.0.7 on 2024-07-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0018_remove_leave_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Re',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=100)),
                ('backlog_course_code', models.CharField(max_length=50)),
                ('backlog_subject', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
